---
name: Build and Push multi-arch Docker image

on:
  release:
    types:
      - released
#      - published

jobs:
  build-publish-linux:
    name: Build and Publish Containers
    runs-on: ubuntu-latest
    steps:
      - name: Set release version
        run: |
          echo "RELEASE_VERSION=$(echo '${{ github.event.release.tag_name }}' | sed -e s/^v//)" >> $GITHUB_ENV
      - name: Print release version
        run: |
          echo ${{ env.RELEASE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: linux/Dockerfile
#          build-args: |
#            BASE=${{ matrix.base }}
          platforms: linux/amd64,linux/arm64/8
          push: true
          tags: gesellix/npipe:${{ env.RELEASE_VERSION }}-linux
  build-publish-windows:
    name: Build and Publish Containers
    runs-on: windows-2022
    steps:
      - name: Set release version
        run: |
          echo "RELEASE_VERSION=$(echo '${{ github.event.release.tag_name }}' | sed -e s/^v//)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Print release version
        run: |
          echo ${{ env.RELEASE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: |
          docker build -f windows/Dockerfile -t gesellix/npipe:${{ env.RELEASE_VERSION }}-windows .
#          docker build -f windows/Dockerfile --build-arg BASE=${{ matrix.base }} -t gesellix/npipe:${{ env.RELEASE_VERSION }}-windows .
      - name: Docker Push
        run: |
          docker push gesellix/npipe:${{ env.RELEASE_VERSION }}-windows

  publish-manifest:
    name: Publish Manifest
    runs-on: ubuntu-latest
    needs:
      - build-publish-linux
      - build-publish-windows
    steps:
      - name: Set release version
        run: |
          echo "RELEASE_VERSION=$(echo '${{ github.event.release.tag_name }}' | sed -e s/^v//)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Manifest
        run: |
          docker manifest create gesellix/npipe:${{ env.RELEASE_VERSION }} \
            --amend gesellix/npipe:${{ env.RELEASE_VERSION }}-linux \
            --amend gesellix/npipe:${{ env.RELEASE_VERSION }}-windows
#      - name: Docker Annotate
#        run: |
#          docker manifest annotate --os windows --arch amd64 \
#            --os-version "10.0.20348.169"\
#            gesellix/npipe:${{ env.RELEASE_VERSION }} gesellix/npipe:${{ env.RELEASE_VERSION }}-windows-amd64
      - name: Docker Push
        run: |
          docker manifest push gesellix/npipe:${{ env.RELEASE_VERSION }}
...
